[cdn]

[matchmaker]
	[matchmaker.game_modes.default]
		tier = "basic-1d2"
		max_players = 32

		[matchmaker.game_modes.default.docker]
			network_mode = "host"

			[matchmaker.game_modes.default.docker.ports]
				signaling = { proto = "https", target = 80 }
				webrtc = { proto = "udp", range = { min = 26000, max = 31999 } }

