[cdn]

[matchmaker]
	tier = "basic-1d4"
	max_players = 32

[matchmaker.regions]
	lnd-sfo = {}
	lnd-fra = {}

[matchmaker.docker]
	network_mode = "host"
	ports.signaling = { protocol = "https", port = 80, dev_port = 3000 }
	ports.webrtc = { protocol = "udp", port_range = { min = 26000, max = 31999 } }

[matchmaker.game_modes]
  default = {}

